In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [5]:
# get working directory and remove last folder
# TODO: make this more robust
wd = os.path.dirname(os.getcwd())
os.chdir(wd)
print("Working Directory: ", os.getcwd())

# the working directory should be .../student-performance

Working Directory:  /Users/marvin/workspace/kaggle_gameplay/student-performance


In [15]:
df = pd.read_csv("data/processed/df_0_4_flattened.csv", index_col=0)
df.head()

session_id_1 level_group_1  event_name_1  name_1  fqid_1  room_fqid_1   
0  20090312431273200           0-4             6       3       5            1  \
1  20090312433251036           0-4             5       3       4            1   
2  20090312455206810           0-4             5       3       4            1   
3  20090313091715820           0-4             5       3       4            1   
4  20090313571836404           0-4             5       3       5            1   

   text_fqid_1  fullscreen_1  hq_1  music_1  ...  room_coor_x_std_5   
0            6             0     0        1  ...         422.014526  \
1            4             0     0        0  ...         352.261993   
2            4             1     1        1  ...         284.153931   
3            4             1     1        1  ...         337.755798   
4            6             0     0        1  ...         395.347290   

   room_coor_y_std_5  screen_coor_x_std_5  screen_coor_y_std_5   
0          41.143421           181.938446            39.566540  \
1          63.718025           181.674881            68.807640   
2          34.723782           197.985825            54.664265   
3         117.306465           187.151123           129.229507   
4          57.395401           155.039871            56.676224   

   hover_duration_std_5  difference_clicks_std_5  index_sum_of_actions_5   
0            164.755875                 8.380692                    13.0  \
1             -1.000000                10.578836                    12.0   
2             -1.000000                 7.594211                    14.0   
3             -1.000000                12.563816                    14.0   
4            625.082397                 9.021479                    12.0   

   difference_clicks_max_5  elapsed_time_max_5  clicks_per_second_5  
0                30.837000           38.620998             0.336604  
1                37.409000           47.641998             0.251879  
2                28.743999           40.616001             0.344692  
3                47.848999           60.853001             0.230063  
4                31.920000           41.750999             0.287418  

[5 rows x 104 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23562 entries, 0 to 23561
Columns: 104 entries, session_id_1 to clicks_per_second_5
dtypes: float64(70), int64(33), object(1)
memory usage: 18.9+ MB


In [12]:
X = df.iloc[:, 2:10].values
print(type(X))
print(X.shape)
print(X)

<class 'numpy.ndarray'>
(23562, 8)
[[6 3 5 ... 0 0 1]
 [5 3 4 ... 0 0 0]
 [5 3 4 ... 1 1 1]
 ...
 [5 3 5 ... 0 0 1]
 [7 3 6 ... 0 0 1]
 [7 3 6 ... 0 0 1]]


In [16]:
labels = pd.read_csv("data/processed/labels.csv")
labels.head()


session  correct  q
0  20090312431273200        1  1
1  20090312433251036        0  1
2  20090312455206810        1  1
3  20090313091715820        0  1
4  20090313571836404        1  1

In [18]:
print(labels.shape)
labels.info()

(424116, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 424116 entries, 0 to 424115
Data columns (total 3 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   session  424116 non-null  int64
 1   correct  424116 non-null  int64
 2   q        424116 non-null  int64
dtypes: int64(3)
memory usage: 9.7 MB


In [29]:
y = labels[(labels['q'] >= 0) & (labels['q'] <= 3)]
y = y['correct'].values
print(y.shape)
print(y)

(70686,)
[1 0 1 ... 1 1 0]


In [9]:

 

 
# Creating training and test split
 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1, stratify = y)
 
# Feature Scaling
 
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)
 
# Training a SVM classifier using SVC class
svm = SVC(kernel= 'linear', random_state=1, C=0.1)
svm.fit(X_train_std, y_train)
 
# Mode performance
 
y_pred = svm.predict(X_test_std)
print('Accuracy: %.3f' % accuracy_score(y_test, y_pred))

NameError: name 'y' is not defined